# Generated by Django 5.2.4 on 2025-07-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
    ]
