# Generated by Django 5.2.4 on 2025-07-21 11:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': '1. Course Categories',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '2.Rating ',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('learning_outcomes', models.JSONField()),
                ('thumbnail', models.ImageField(upload_to='course_images/')),
                ('teacher', models.ManyToManyField(to='Teacher.teacher')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory')),
                ('rating', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.rating')),
            ],
            options={
                'verbose_name_plural': '3. Course ',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name_plural': '6. Cart ',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.course')),
            ],
            options={
                'verbose_name_plural': '4.Topics ',
            },
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', cloudinary.models.CloudinaryField(max_length=255)),
                ('video_length', models.TimeField(default='00:00:00')),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnail/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.topic')),
            ],
            options={
                'verbose_name_plural': '5.Lecture Videos ',
            },
        ),
        migrations.CreateModel(
            name='Student_enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Student.student')),
            ],
            options={
                'verbose_name_plural': '7. Student Enrollment',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
